version: '3.8'

services:

  app:
    image: $IMAGE_TAG:$GITHUB_REF_NAME-$GITHUB_RUN_ID
    ports:
      - "5000:8000"
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app
    restart: always

  nginx:
    image: nginx:1.19.3
    ports:
      - 80:80
    volumes:
      - .nginx.conf:/etc/nginx/conf.d/default.conf
    restart: always
