name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: build docker
        run: docker build -t ${{ secret.IMAGE_TAG }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
      - name: docker login
        run: docker login -u ${{ secret.DOCKER_LOGIN }} -p ${{ secret.DOCKER_PASSWORD }}
      - name: push
        run: docker push ${{ secret.IMAGE_TAG }}:$GITHUB_REF_NAME-$GITHUB_RUN_ID
